version: '3.8'
services:
  gcp-identity-platform-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8080:8080"
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped

networks:
  default:
      name: gcp-identity-platform-network